Make scripts handle SIGTERM safely

diff --git a/monitoring/openshift/cronjobs/cron-scripts/hard-prune b/monitoring/openshift/cronjobs/cron-scripts/hard-prune
--- a/monitoring/openshift/cronjobs/cron-scripts/hard-prune
+++ b/monitoring/openshift/cronjobs/cron-scripts/hard-prune
@@ -1,45 +1,61 @@
 #!/usr/bin/env bash
-NOOP=
+# Exit on error. Append "|| true" if you expect an error.
+set -o errexit
+# Exit on error inside any functions or subshells.
+set -o errtrace
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+set -o nounset
+# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
+set -o pipefail
+# Turn on traces, useful while debugging but commented out by default
+# set -o xtrace
+
+# Safely exit if timed out
+function safe_exit () {
+  trap '' INT TERM # ignore INT and TERM while shutting down
+  echo "Trapped SIGTERM in script and cleaning up"
+  kill -TERM $BG_PID # Kill backgrounded script
+  wait $BG_PID # Wait for it to exit
+  oc set env -n default dc/docker-registry REGISTRY_STORAGE_MAINTENANCE_READONLY-
+  oc rollout status dc/docker-registry -n default
+  exit 1
+}
+
+trap safe_exit SIGTERM
+
 timestamp() { date +"%Y-%m-%d %H:%M:%S %Z"; }
 PRUNE_OPTIONS="--keep-younger-than=96h --loglevel=4"
-# perform basic prune (do not trigger rollout as that will occur with readonly mode change)
-# Prune
-echo "$(timestamp): oc adm prune images ${PRUNE_OPTIONS}"
-oc adm prune images --force-insecure ${PRUNE_OPTIONS}
-rc=$?
-if [ $rc -ne 0 ] ; then
-  echo "$(timestamp): Dry-Run Prune failed, aborting..."
-  exit $rc
-fi
-echo "$(timestamp) oc adm prune images ${PRUNE_OPTIONS} --confirm"
-${NOOP} oc adm prune images --force-insecure ${PRUNE_OPTIONS} --confirm
-rc=$?
-if [ $rc -ne 0 ] ; then
-  echo "$(timestamp): Prune failed, aborting..."
-  exit $rc;
-fi
+
 echo $(timestamp)
 # switch registry to read-only mode (will trigger a redeploy)
-${NOOP} oc env -n default dc/docker-registry 'REGISTRY_STORAGE_MAINTENANCE_READONLY={"enabled":true}'
-# (if required: oc rollout latest dc/docker-registry -n default)
-oc rollout status dc/docker-registry -n default
-sleep 5 # rollout may have some pods still spinning up
+oc set env -n default dc/docker-registry 'REGISTRY_STORAGE_MAINTENANCE_READONLY={"enabled":true}'
+# oc rollout latest dc/docker-registry -n default
+oc rollout status dc/docker-registry -n default &
+BG_PID=`jobs -p`
+wait $BG_PID
+sleep 600 # rollout may have some pods still spinning up
+
 echo $(timestamp)
 oc -n default exec "$(oc -n default get pods -l deploymentconfig=docker-registry \
   -o jsonpath=$'{.items[?(.status.phase=="Running")].metadata.name}'| cut -d " " -f1)" \
-  -- /usr/bin/dockerregistry -prune=check
+  -- /usr/bin/dockerregistry -prune=check &
+BG_PID=`jobs -p`
+wait $BG_PID
 rc=$?
+
 echo $(timestamp)
 if [ $rc -eq 0 ] ; then
-  ${NOOP} oc -n default exec "$(oc -n default get pods -l deploymentconfig=docker-registry \
+  oc -n default exec "$(oc -n default get pods -l deploymentconfig=docker-registry \
     -o jsonpath=$'{.items[?(.status.phase=="Running")].metadata.name}'| cut -d " " -f1)" \
-    -- /usr/bin/dockerregistry -prune=delete
+    -- /usr/bin/dockerregistry -prune=delete &
+    BG_PID=`jobs -p`
+    wait $BG_PID
     rc=$?
 else
   echo "$(timestamp): Hard prune check failed, skipping prune delete"
 fi
+
 echo $(timestamp)
 # Switch registry back to read-write mode
-${NOOP} oc env -n default dc/docker-registry REGISTRY_STORAGE_MAINTENANCE_READONLY-
+oc set env -n default dc/docker-registry REGISTRY_STORAGE_MAINTENANCE_READONLY-
 oc rollout status dc/docker-registry -n default && exit $rc
-
