Change hard-prune to not run if check fails

diff --git a/monitoring/openshift/cronjobs/cm-registry-hard-prune.yaml b/monitoring/openshift/cronjobs/cm-registry-hard-prune.yaml
--- a/monitoring/openshift/cronjobs/cm-registry-hard-prune.yaml
+++ b/monitoring/openshift/cronjobs/cm-registry-hard-prune.yaml
@@ -38,10 +38,16 @@ objects:
       oc -n default exec "$(oc -n default get pods -l deploymentconfig=docker-registry \
         -o jsonpath=$'{.items[?(.status.phase=="Running")].metadata.name}'| cut -d " " -f1)" \
         -- /usr/bin/dockerregistry -prune=check
+      rc=${PIPESTATUS[0]}
       echo $(timestamp)
-      ${NOOP} oc -n default exec "$(oc -n default get pods -l deploymentconfig=docker-registry \
-        -o jsonpath=$'{.items[?(.status.phase=="Running")].metadata.name}'| cut -d " " -f1)" \
-        -- /usr/bin/dockerregistry -prune=delete
+      if [ $rc -eq 0 ] ; then
+        ${NOOP} oc -n default exec "$(oc -n default get pods -l deploymentconfig=docker-registry \
+          -o jsonpath=$'{.items[?(.status.phase=="Running")].metadata.name}'| cut -d " " -f1)" \
+          -- /usr/bin/dockerregistry -prune=delete
+      else
+        echo "$(timestamp): Hard prune check failed, skipping prune delete"
+        exit $rc;
+      fi
       echo $(timestamp)
       # Switch registry back to read-write mode
       ${NOOP} oc env -n default dc/docker-registry REGISTRY_STORAGE_MAINTENANCE_READONLY-
