Send email for ERROR level events

diff --git a/utils/ansible-playbooks/deploy-monitoring/templates/ocp-monitor.j2 b/utils/ansible-playbooks/deploy-monitoring/templates/ocp-monitor.j2
--- a/utils/ansible-playbooks/deploy-monitoring/templates/ocp-monitor.j2
+++ b/utils/ansible-playbooks/deploy-monitoring/templates/ocp-monitor.j2
@@ -153,39 +153,49 @@ function return_node_ready_count () {
 
 # Test that the API is responding
 echo -n "$(datestamp) OpenShift API Status: "
-if ! ${CURL} {{ api_url }}/healthz | grep ok
+if ! STATUS=$(${CURL} {{ api_url }}/healthz 2>&1 | grep ok)
 then
-  echo "$(datestamp) ERROR: curl of API {{ api_url }}/healthz failed"
+  echo -e "${STATUS}"
+  MSG=$(echo "$(datestamp) ERROR: curl of API {{ api_url }}/healthz failed")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for API Status Check on `hostname`" $MAILTO
+else
+  echo -e "${STATUS}"
 fi
 
 {% if ansible_fqdn == primary_master %}
 # Test that the Router service is responding
 echo -n "$(datestamp) OpenShift Router Status: "
-if ! ${CURL} http://router.default.svc:1936/healthz | grep 'Service ready'
+if ! STATUS=$(${CURL} http://router.default.svc:1936/healthz 2>&1 | grep -i OK)
 then
-  echo "$(datestamp) ERROR: curl of router service http://router.default.svc:1936/healthz failed"
+  MSG=$(echo -e "\n$(datestamp) ERROR: curl of router service http://router.default.svc:1936/healthz failed\n${STATUS}")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for Router Status Check on `hostname`" $MAILTO
+else
+  echo -e "${STATUS}"
 fi
 
 # Test that a sample route is working
 echo "$(datestamp) Canary Route Status"
 get_state canaryhealth CANARY_HEALTH_STATE
 # Use --insecure in case there are TLS cert issues
-if [[ ! $(${CURL} --head --insecure {{ canary_route }} | grep '200 OK') ]]; then
+if ! STATUS=$(${CURL} --head --insecure {{ canary_route }} 2>&1 | grep '200 OK'); then
 
   if [[ "${CANARY_HEALTH_STATE}" -eq "0" ]]; then
 # canary health check failure while in state 0, bumps us to state 1 and warns only
     set_state canaryhealth 1
-    MSG=$(echo "$(datestamp) WARN: curl of {{ canary_route }} failed")
+    MSG=$(echo -e "$(datestamp) WARN: curl of {{ canary_route }} failed\n${STATUS}")
     echo -e "${MSG}"
     echo -e "${MSG}" | mail -s "WARN event for CanaryHealthCheck on `hostname`" $MAILTO
   elif [[ "${CANARY_HEALTH_STATE}" -eq "1" ]]; then
 # canary health check failure while in state 1, bumps us to state 2 and alerts oncall with error
     set_state canaryhealth 2
-    MSG=$(echo "$(datestamp) ERROR: curl of {{ canary_route }} failed")
+    MSG=$(echo -e "$(datestamp) ERROR: curl of {{ canary_route }} failed\n${STATUS}")
     echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "ERROR event for CanaryHealthCheck on `hostname`" $MAILTO
   elif [[ "${CANARY_HEALTH_STATE}" -eq "2" ]]; then
 # canary health check failure while in state 2, no state change. Still will alert though.
-    MSG=$(echo "$(datestamp) ERROR: curl of {{ canary_route }} failed")
+    MSG=$(echo -e "$(datestamp) ERROR: curl of {{ canary_route }} failed\n${STATUS}")
     echo -e "${MSG}"
   fi
 else
@@ -207,9 +217,13 @@ fi
 # TOD switch to DNS name once server is using dnsmasq properly
 echo -n "$(datestamp) Docker Registry Status: "
 # Use --head as this enpoint returns an empty document
-if ! ${CURL} --head {{ registry_service }}/healthz | grep '200 OK'
+if ! STATUS=$(${CURL} --head {{ registry_service }}/healthz 2>&1 | grep '200 OK')
 then
-  echo "$(datestamp) ERROR: curl of docker registry service {{ registry_service }}/healthz failed"
+  MSG=$(echo -e"\n$(datestamp) ERROR: curl of docker registry service {{ registry_service }}/healthz failed\n${STATUS}")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for Registry Status Check on `hostname`" $MAILTO
+else
+  echo -e "${STATUS}"
 fi
 
 # Run provided metrics health check
@@ -218,19 +232,20 @@ DIR=$(dirname $(readlink -f "$0"))
 get_state metricshealth METRICS_HEALTH_STATE
 
 echo "$(datestamp) Metrics Status"
-if [[ ! $(/usr/local/bin/metrics-health-check {{ metrics_url }} | grep '200 Ok') ]]; then
+if ! STATUS=$(/usr/local/bin/metrics-health-check {{ metrics_url }} 2>&1 | grep '200 Ok'); then
 
   if [[ "${METRICS_HEALTH_STATE}" -eq "0" ]]; then
 # metrics health check failure while in state 0, bumps us to state 1 and warns only
     set_state metricshealth 1
-    MSG=$(echo "$(datestamp) WARN: Metrics health check failed")
+    MSG=$(echo -e "$(datestamp) WARN: Metrics health check failed\n${STATUS}")
     echo -e "${MSG}"
     echo -e "${MSG}" | mail -s "WARN event for MetricsHealthCheck on `hostname`" ${MAILTO}
   elif [[ "${METRICS_HEALTH_STATE}" -eq "1" ]]; then
 # metrics health check failure while in state 1, bumps us to state 2 and alerts oncall with error
     set_state metricshealth 2
-    MSG=$(echo "$(datestamp) ERROR: Metrics health check failed")
+    MSG=$(echo -e "$(datestamp) ERROR: Metrics health check failed\n${STATUS}")
     echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "ERROR event for MetricsHealthCheck on `hostname`" ${MAILTO}
   elif [[ "${METRICS_HEALTH_STATE}" -eq "2" ]]; then
 # metrics health check failure while in state 2, no state change. Still will alert though.
     MSG=$(echo "$(datestamp) ERROR: Metrics health check failed")
@@ -259,7 +274,9 @@ echo "$(echo 100 '-' $SPACE | bc -l)% free"
 FREE=$(echo 100 '-' $SPACE '>' 15 | bc -l)
 if [ "$FREE" -lt 1 ]
 then
-  echo "$(datestamp) ERROR: Low Docker Registry Space"
+  MSG=$(echo "$(datestamp) ERROR: Low Docker Registry Space")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for Registry Space on `hostname`" $MAILTO
 fi
 
 # Check disk space of Metrics Cassandra
@@ -270,7 +287,9 @@ echo "$(echo 100 '-' $SPACE | bc -l)% free"
 FREE=$(echo 100 '-' $SPACE '>' 15 | bc -l)
 if [ "$FREE" -lt 1 ]
 then
-  echo "$(datestamp) ERROR: Low Metrics Cassandra Space"
+  MSG=$(echo "$(datestamp) ERROR: Low Metrics Cassandra Space")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for Cassandra Space on `hostname`" $MAILTO
 fi
 
 {% raw %}
@@ -301,6 +320,7 @@ if [[ "$(test_if_all_nodes_are_ready)" -eq "0" ]]; then
     MSG="${MSG}\n${CURRENT_NODE_STATE}"
     MSG="${MSG}\n`oc get events -n default`"
     echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "ERROR event for NodeNotReady on `hostname`" ${MAILTO}
   elif [[ "${NODE_READY_STATE}" -eq "2" ]]; then
 # node ready failure while in state 2, no state change. Still will alert though.
     MSG=$(echo "$(datestamp) ERROR: Some nodes are not Ready")
@@ -361,6 +381,7 @@ if [[ ("${POD_COUNT}" -lt 3) || ("${UNIQ_NODES}" -lt 3) ]]; then
 # for convenience include actual pod status for registry pods to save time investigating
     MSG="${MSG}\n$(oc -n default get pods -o wide -l deploymentconfig=docker-registry)"
     echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "ERROR event for RegistryPodCheck on $(hostname)" ${MAILTO}
   elif [[ "${REGISTRY_POD_STATE}" -eq "2" ]]; then
 # health check failure while in state 2, no state change. Still will alert though.
     if [[ ("${POD_COUNT}" -lt 3) && ("${UNIQ_NODES}" -lt 3) ]]; then
@@ -425,6 +446,7 @@ if [[ ("${POD_COUNT}" -lt 3) || ("${UNIQ_NODES}" -lt 3) ]]; then
 # for convenience include actual pod status for Router pods to save time investigating
     MSG="${MSG}\n$(oc -n default get pods -o wide -l deploymentconfig=router)"
     echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "ERROR event for RouterPodCheck on $(hostname)" ${MAILTO}
   elif [[ "${ROUTER_POD_STATE}" -eq "2" ]]; then
 # health check failure while in state 2, no state change. Still will alert though.
     if [[ ("${POD_COUNT}" -lt 3) && ("${UNIQ_NODES}" -lt 3) ]]; then
@@ -493,6 +515,7 @@ if [[ ("${POD_COUNT}" -lt 3) || ("${UNIQ_NODES}" -lt 3) ]]; then
 # for convenience include actual pod status for IPF pods to save time investigating
     MSG="${MSG}\n$(oc -n default get pods -o wide -l deploymentconfig=${ROUTER_DC})"
     echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "ERROR event for IPFPodCheck on $(hostname)" ${MAILTO}
   elif [[ "${IPF_POD_STATE}" -eq "2" ]]; then
 # health check failure while in state 2, no state change. Still will alert though.
     if [[ ("${POD_COUNT}" -lt 3) && ("${UNIQ_NODES}" -lt 3) ]]; then
@@ -574,6 +597,7 @@ if [ "${CPU_PERCENT}" -gt ${CPU_CAPACITY_THRESHOLD} ]; then
     set_state clustercpucapacity 2
     MSG=$(echo "$(datestamp) ERROR: Cluster low on CPU capacity - over the threshold of ${CPU_CAPACITY_THRESHOLD}%")
     echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "ERROR event for CPUCapacityCheck on $(hostname)" ${MAILTO}
   elif [[ "${CPU_CAPACITY_STATE}" -eq "2" ]]; then
     MSG=$(echo "$(datestamp) ERROR: Cluster low on CPU capacity - over the threshold of ${CPU_CAPACITY_THRESHOLD}%")
     echo -e "${MSG}"
@@ -614,6 +638,7 @@ if [ "${MEM_PERCENT}" -gt ${MEM_CAPACITY_THRESHOLD} ]; then
     set_state clusterramcapacity 2
     MSG=$(echo "$(datestamp) ERROR: Cluster low on Memory capacity - over the threshold of ${MEM_CAPACITY_THRESHOLD}%")
     echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "ERROR event for MemoryCapacityCheck on $(hostname)" ${MAILTO}
   elif [[ "${MEM_CAPACITY_STATE}" -eq "2" ]]; then
     MSG=$(echo "$(datestamp) ERROR: Cluster low on Memory capacity - over the threshold of ${MEM_CAPACITY_THRESHOLD}%")
     echo -e "${MSG}"
@@ -654,6 +679,7 @@ if [ "${POD_PERCENT}" -gt ${POD_CAPACITY_THRESHOLD} ]; then
     set_state clusterpodcapacity 2
     MSG=$(echo "$(datestamp) ERROR: Cluster low on Pod capacity - over the threshold of ${POD_CAPACITY_THRESHOLD}%")
     echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "ERROR event for PodCapacityCheck on $(hostname)" ${MAILTO}
   elif [[ "${POD_CAPACITY_STATE}" -eq "2" ]]; then
     MSG=$(echo "$(datestamp) ERROR: Cluster low on Pod capacity - over the threshold of ${POD_CAPACITY_THRESHOLD}%")
     echo -e "${MSG}"
@@ -686,10 +712,10 @@ do
   for SERVICE in tcmu-runner gluster-block-target gluster-blockd
   do
     echo -n "$(datestamp) Status of ${SERVICE} on ${POD}: "
-    if ! oc exec -n cns ${POD} -- /bin/bash -c 'systemctl is-active '${SERVICE}'.service'
+    if ! STATUS=$(oc exec -n cns ${POD} -- /bin/bash -c 'systemctl is-active '${SERVICE}'.service' 2>&1)
     then
         MSG=$(echo "$(datestamp) WARN: ${SERVICE} on CNS pod ${POD} is unhealthy")
-        MSG="${MSG}\n$(oc exec -n cns ${POD} -- /bin/bash -c 'systemctl status '${SERVICE}'.service' || true)"
+        MSG="${MSG}\n${STATUS}\n$(oc exec -n cns ${POD} -- /bin/bash -c 'systemctl status '${SERVICE}'.service' 2>&1 || true)"
         echo -e "${MSG}"
         echo -e "${MSG}" | mail -s "WARN event for CNS service check on pod ${POD}" ${MAILTO}
     else
@@ -746,23 +772,38 @@ done
 {% raw %}
 # Verify ETCD is running
 echo -n "$(datestamp) ETCD Deamon Status: "
-if ! systemctl is-active etcd.service
+if ! STATUS=$(systemctl is-active etcd.service 2>&1)
 then
-  echo "$(datestamp) ERROR: ETCD is not running"
+  echo -e "${STATUS}"
+  MSG=$(echo "$(datestamp) ERROR: ETCD is not running")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for ETCD Deamon Status Check on `hostname`" $MAILTO
+else
+  echo -e "${MSG}"
 fi
 
 # Verify API service is running
 echo -n "$(datestamp) OpenShift API Deamon Status: "
-if ! systemctl is-active atomic-openshift-master-api.service
+if ! STATUS=$(systemctl is-active atomic-openshift-master-api.service 2>&1)
 then
-  echo "$(datestamp) ERROR: OpenShift API is not running"
+  echo -e "${STATUS}"
+  MSG=$(echo "$(datestamp) ERROR: OpenShift API Deamon is not running")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for OpenShift API Deamon Status Check on `hostname`" $MAILTO
+else
+  echo -e "${MSG}"
 fi
 
 # Verify Controller service is running
 echo -n "$(datestamp) OpenShift Controller Deamon Status: "
-if ! systemctl is-active atomic-openshift-master-controllers.service
+if ! STATUS=$(systemctl is-active atomic-openshift-master-controllers.service 2>&1)
 then
-  echo "$(datestamp) ERROR: OpenShift Controller is not running"
+  echo -e "${STATUS}"
+  MSG=$(echo "$(datestamp) ERROR: OpenShift Controller is not running")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for OpenShift Controller Deamon Status Check on `hostname`" $MAILTO
+else
+  echo -e "${MSG}"
 fi
 {% endraw %}
 {% endif %}
@@ -800,11 +841,16 @@ fi
 
 # Check Docekr is running
 echo -n "$(datestamp) Docker Deamon Status: "
-if ! systemctl is-active docker.service
+if ! STATUS=$(systemctl is-active docker.service 2>&1)
 then
-  echo "$(datestamp) ERROR: Docker is not running"
+  echo -e "${STATUS}"
+  MSG=$(echo "$(datestamp) ERROR: Docker is not running")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for Docker Deamon Status Check on `hostname`" $MAILTO
   # Other checks depend on Docker running, exit out
   exit 1
+else
+  echo -e "${MSG}"
 fi
 
 # Check Docker Data usage
@@ -814,7 +860,10 @@ echo "$SPACE = $(echo $SPACE '*' 100 | bc -l | awk '{printf "%.2f",$0}')% free"
 FREE=$(echo $SPACE '>' 0.15 | bc -l)
 if [ "$FREE" -lt 1 ]
 then
-  echo "$(datestamp) ERROR: Low Docker Data Space"
+  MSG=$(echo "$(datestamp) ERROR: Low Docker Data Space")
+  MSG="{MSG}\n$(docker info | grep 'Data Space')"
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for Docker Data Space Check on `hostname`" $MAILTO
 fi
 
 # Check Docker Metadata Usage
@@ -824,7 +873,10 @@ echo "$SPACE = $(echo $SPACE '*' 100 | bc -l | awk '{printf "%.2f",$0}')% free"
 FREE=$(echo $SPACE '>' 0.15 | bc -l)
 if [ "$FREE" -lt 1 ]
 then
-  echo "$(datestamp) ERROR: Low Docker Metadata Space"
+  MSG=$(echo "$(datestamp) ERROR: Low Docker Metadata Space")
+  MSG="{MSG}\n$(docker info | grep 'Metadata Space')"
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for Docker Metadata Space Check on `hostname`" $MAILTO
 fi
 
 # Check for local volume count
@@ -833,21 +885,33 @@ VOLS=$(mount|grep -c openshift.local.volumes||true)
 echo "$(datestamp) Pod volumes: $VOLS"
 if [ "$VOLS" -gt "1000" ]
 then
-  echo "$(datestamp) ERROR: Too many volumes"
+  MSG=$( echo "$(datestamp) ERROR: Too many volumes")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for PodVolume Check on `hostname`" $MAILTO
 fi
 
 # Check Node service
 echo -n "$(datestamp) OpenShift Node Deamon Status: "
-if ! systemctl is-active atomic-openshift-node.service
+if ! STATUS=$(systemctl is-active atomic-openshift-node.service 2>&1)
 then
-  echo "$(datestamp) ERROR: OpenShift Node is not running"
+  echo -e "${STATUS}"
+  MSG=$(echo "$(datestamp) ERROR: OpenShift Node is not running")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for Node Deamon Status Check on `hostname`" $MAILTO
+else
+  echo -e "${MSG}"
 fi
 
 # Check OpenVSwitch service
 echo -n "$(datestamp) OpenVSwitch Deamon Status: "
-if ! systemctl is-active openvswitch.service
+if ! STATUS=$(systemctl is-active openvswitch.service 2>&1)
 then
-  echo "$(datestamp) ERROR: OpenVSwitch is not running"
+  echo -e "${STATUS}"
+  MSG=$(echo "$(datestamp) ERROR: OpenVSwitch is not running")
+  echo -e "${MSG}"
+  echo -e "${MSG}" | mail -s "ERROR event for OpenVSwitch Deamon Status Check on `hostname`" $MAILTO
+else
+  echo -e "${MSG}"
 fi
 
 # Check and return applicable PIDs matching docker-containerd-current. If nothing is returned, then it may have been killed off.
