Added stateful checks for infra registry pod health checkss

diff --git a/utils/ansible-playbooks/deploy-monitoring/templates/ocp-monitor.j2 b/utils/ansible-playbooks/deploy-monitoring/templates/ocp-monitor.j2
--- a/utils/ansible-playbooks/deploy-monitoring/templates/ocp-monitor.j2
+++ b/utils/ansible-playbooks/deploy-monitoring/templates/ocp-monitor.j2
@@ -19,6 +19,7 @@ MSG=""
 MAILTO="william.hutchison@dxcas.com steven.barre@dxcas.com"
 CANARY_HEALTH_STATE="0"
 METRICS_HEALTH_STATE="0"
+REGISTRY_POD_STATE="0"
 
 {% raw %}
 bash_backtrace() {
@@ -307,16 +308,67 @@ fi
 
 # Verify the Registry is on 3 nodes
 NODES=$(oc -n default get pods -l deploymentconfig=docker-registry -o yaml -o go-template="{{range .items}}{{if eq .status.phase \"Running\"}}{{.spec.nodeName}}{{print \"\n\"}}{{end}}{{end}}")
-POD_COUNT=$(echo "$NODES" | wc -l)
-UNIQ_NODES=$(echo "$NODES" | sort | uniq | wc -l)
-echo "$(datestamp) Check that Registry is scaled to 3: $POD_COUNT"
-echo "$(datestamp) Check that Registry is scaled to all infra nodes: " $UNIQ_NODES
-if [ "$POD_COUNT" -lt 3 ]
-then
-  echo "$(datestamp) ERROR: Registry pod count $POD_COUNT is less than 3"
-elif [ "$UNIQ_NODES" -lt 3 ]
-then
-  echo "$(datestamp) ERROR: Registry on too few nodes " $NODES
+POD_COUNT=$(echo "${NODES}" | wc -l)
+UNIQ_NODES=$(echo "${NODES}" | sort | uniq | wc -l)
+echo "$(datestamp) Check that Registry is scaled to 3: ${POD_COUNT}"
+echo "$(datestamp) Check that Registry is scaled to all infra nodes: " ${UNIQ_NODES}
+get_state registrypodcount REGISTRY_POD_STATE
+if [[ ("${POD_COUNT}" -lt 3) || ("${UNIQ_NODES}" -lt 3) ]]; then
+
+  if [[ "${REGISTRY_POD_STATE}" -eq "0" ]]; then
+# health check failure while in state 0, bumps us to state 1 and warns only
+    set_state registrypodcount 1
+    if [[ ("${POD_COUNT}" -lt 3) && ("${UNIQ_NODES}" -lt 3) ]]; then
+      MSG=$(echo "$(datestamp) WARN: Registry pod count ${POD_COUNT} is less than 3 and Registry on too few infra nodes: " ${NODES})
+    elif [[ "${POD_COUNT}" -lt 3 ]]; then
+      MSG=$(echo "$(datestamp) WARN: Registry pod count ${POD_COUNT} is less than 3")
+    elif [[ "${UNIQ_NODES}" -lt 3 ]]; then
+      MSG=$(echo "$(datestamp) WARN: Registry running on too few infra nodes " ${NODES})
+    fi
+# for convenience include actual pod status for registry pods to save time investigating
+    MSG="${MSG}\n$(oc -n default get pods -o wide -l deploymentconfig=docker-registry)"
+    echo -e "${MSG}"
+    echo -e "${MSG}" | mail -s "WARN event for RegistryPodCheck on $(hostname)" ${MAILTO}
+  elif [[ "${REGISTRY_POD_STATE}" -eq "1" ]]; then
+# health check failure while in state 1, bumps us to state 2 and alerts oncall with error
+    set_state registrypodcount 2
+    if [[ ("${POD_COUNT}" -lt 3) && ("${UNIQ_NODES}" -lt 3) ]]; then
+      MSG=$(echo "$(datestamp) ERROR: Registry pod count ${POD_COUNT} is less than 3 and Registry running on too few infra nodes: " ${NODES})
+    elif [[ "${POD_COUNT}" -lt 3 ]]; then
+      MSG=$(echo "$(datestamp) ERROR: Registry pod count ${POD_COUNT} is less than 3")
+    elif [[ "${UNIQ_NODES}" -lt 3 ]]; then
+      MSG=$(echo "$(datestamp) ERROR: Registry running on too few infra nodes " ${NODES})
+    fi
+# for convenience include actual pod status for registry pods to save time investigating
+    MSG="${MSG}\n$(oc -n default get pods -o wide -l deploymentconfig=docker-registry)"
+    echo -e "${MSG}"
+  elif [[ "${REGISTRY_POD_STATE}" -eq "2" ]]; then
+# health check failure while in state 2, no state change. Still will alert though.
+    if [[ ("${POD_COUNT}" -lt 3) && ("${UNIQ_NODES}" -lt 3) ]]; then
+      MSG=$(echo "$(datestamp) ERROR: Registry pod count ${POD_COUNT} is less than 3 and Registy running on too few infra nodes: " ${NODES})
+    elif [[ "${POD_COUNT}" -lt 3 ]]; then
+      MSG=$(echo "$(datestamp) ERROR: Registry pod count ${POD_COUNT} is less than 3")
+    elif [[ "${UNIQ_NODES}" -lt 3 ]]; then
+      MSG=$(echo "$(datestamp) ERROR: Registry running on too few infra nodes " ${NODES})
+    fi
+# for convenience include actual pod status for registry pods to save time investigating
+    MSG="${MSG}\n$(oc -n default get pods -o wide -l deploymentconfig=docker-registry)"
+    echo -e "${MSG}"
+  fi
+else
+# Health check passed, adjust state accordingly.
+  if [[ "${REGISTRY_POD_STATE}" -eq "0" ]]; then
+# health check success while in state 0, no state change
+    echo "$(datestamp) INFO: Registry pods are properly scaled"
+  elif [[ "${REGISTRY_POD_STATE}" -eq "1" ]]; then
+# metrics health check success while in state 1, state change back to 0
+    set_state registrypodcount 0
+    echo "$(datestamp) INFO: Registry pods are properly scaled"
+  elif [[ "${REGISTRY_POD_STATE}" -eq "2" ]]; then
+# metrics health check success while in state 2, state change back to 0
+    set_state registrypodcount 0
+    echo "$(datestamp) INFO: Registry pods are properly scaled"
+  fi
 fi
 
 # Verify the Router is on 3 nodes
